version: "3.4"

services:
  srt-wallet:
    container_name: srt-wallet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srt-wallet.rule=PathPrefix(`/`)"
    user: root # avoids ton of volume mounting headaches in dev mode.
    build:
      context: .
      target: build
    volumes:
      - ./:/opt/app
      # @see: http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html#the-node_modules-volume-trick
      - /opt/app/node_modules
    ports:
      - 34129:6001
    environment:
      - NODE_ENV=dev
      - NODE_HOT_RELOAD=1
      - NODE_LOGGER_GRANULARLEVELS=1
      - NODE_CONFIG_DISABLE_FILE_WATCH="Y"
      #- PORT=5502 # this is overriden in shell/start-dev.sh since wait-for.sh compromises it from here
    # @see: https://docs.docker.com/compose/startup-order/
    # command: npm run start
